<?php
	echo("Who Are You ?<br>");
	echo("&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp^<br>");
	echo("&nbsp&nbsp&nbsp&nbsp<&nbsp&nbsp><br>");
	echo("&nbsp&nbsp&nbsp<&nbsp&nbsp&nbsp&nbsp><br>");
	echo("&nbsp&nbsp<&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp><br>");
	echo("&nbsp<&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp><br>");
	echo("&nbsp&nbsp&nbsp-------<br>");
	echo("&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp||<br>");
	echo("&nbsp&nbsp&nbsp&nbsp&nbsp口<br>");
?>
